In [1]:
!pip install opencv-python

In [2]:
import cv2
print('Package imported')
img = cv2.imread('Mouly.JPG')
cv2.imshow('Output', img)
cv2.waitKey(1)


Package imported


-1

In [ ]:
import cv2
cap = cv2.VideoCapture('Cute Cat - 3092.mp4')
while True:
    success, img = cap.read()
    cv2.imshow('Video', img)
    if cv2.waitKey(1) & 0xFF == ord('m'):
        break

In [ ]:
import cv2
cap = cv2.VideoCapture(0)
cap.set(3, 640)
cap.set(4, 480)


while True:
    success, img = cap.read()
    cv2.imshow('Video', img)
    if cv2.waitKey(1) & 0xFF == ord('m'):
        break

In [ ]:
import cv2
import numpy as np
kernel = np.ones((5, 5), np.uint8)
img = cv2.imread('Mouly.JPG')
imgGray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
imgBlur = cv2.GaussianBlur(imgGray,(7,7), 0)
imgCanny = cv2.Canny(img, 150, 200)
imgDilation = cv2.dilate(imgCanny, kernel, iterations = 3)
imgerode = cv2.erode(imgDilation, kernel, iterations = 1)
cv2.imshow('GRAY Image', imgGray)
cv2.imshow('Blur Image', imgBlur)
cv2.imshow('Canny Image', imgCanny)
cv2.imshow('Dilate Image', imgDilation)
cv2.imshow('Eroder Image', imgerode)
cv2.waitKey(0)

In [ ]:
#openCV convention: x axis is same, y axis is towards.

In [ ]:
#resizing image:
import cv2
import numpy as np
img = cv2.imread('Mouly.JPG')
print(img.shape)                  #(6000---> weight, 4000 ---> height, 3---> BGR)
imgResize = cv2.resize(img, (200, 400))  #here, the weight comes first, then the height
print(imgResize.shape)            #(400, 200, 3)
imgCropped = img[0:2000, 200:900]            #here, the height comes first                
cv2.imshow('Image', img)
cv2.imshow('Resize Image', imgResize)
cv2.imshow('Cropped Image', imgCropped)
cv2.waitKey(0)


(6000, 4000, 3)
(400, 200, 3)


In [ ]:
#shapes and texts

In [ ]:
#we will use numpy library to create our img matrix
import cv2
import numpy as np

#img = np.zeros((512, 512))   #it will show a black img, which is gray scale image.
#print(img.shape)
img = np.zeros((512, 512, 3), np.uint8)
#print(img)       #it shows the matrix
#img[:] = 255, 0, 0     #it colors the whole image blue
img[200:600, 100: 500] = 255, 0, 0   #it shows only the portion as blue
print(img)


cv2.imshow('Image', img)
cv2.waitKey(0)


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [ ]:
#creating a line

import cv2
import numpy as np

img = np.zeros((512, 512, 3), np.uint8)
cv2.line(img, (0,0), (400, 400), (0,255,0), 3) #(0,0) starting point, (400, 400) end point, (0,255,0) color, 3--> thickness
#for creating the whole line in picture, we use 'img.shape()'
cv2.line(img,(0,0), (img.shape[1], img.shape[0],), (0, 255, 0), 3) #first width, then height
cv2.rectangle(img,(0,0), (250,350),(0,0,255), 2)
#cv2.rectangle(img,(0,0), (250,350),(0,0,255), cv2.FILLED) #for filling rectangle
cv2.circle(img,(400,50), 30, (255, 255, 0), 5) #(400, 50) center point, 30 --> radius, color, thickness
cv2.putText(img, 'Mouly', (200, 200), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 150,0), 2) #1 --> scale(makes big-small), 2--> thickness
cv2.imshow('Image', img)
cv2.waitKey(0)

In [ ]:
#wrap prespective
import cv2
import numpy as np
img = cv2.imread('openCVking.jpg')

width, height = 250, 350
points = np.float32([[345,122],[580, 82],[409, 450],[636, 409]]) #we are taking four edges points from paints
points2 = np.float32([[0,0],[width, 0], [0,height], [width, height]])
matrix = cv2.getPerspectiveTransform(points, points2)
imgOutput = cv2.warpPerspective(img, matrix,(width, height))

cv2.imshow('Cards', img)
cv2.imshow('Output', imgOutput)
cv2.waitKey(0)

In [ ]:
#joining images(use stack)
import cv2
import numpy as np

img = cv2.imread('Mouly.JPG')
imgHor = np.hstack((img,img,img))
imgVer = np.vstack((img,img))

cv2.imshow('Horizontal',imgHor)
cv2.imshow('Vertical',imgVer)
cv2.waitKey(0)

In [ ]:
#COLOR DETECTION

In [ ]:
import cv2
img = cv2.imread('Mouly.JPG')

imgHSV = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

cv2.imshow('Original', img)
cv2.imshow('HSV', imgHSV)
cv2.waitKey(0)


In [ ]:
#now will create trackbars for adjusting this HSV colors.
import cv2
path = 'Mouly.JPG'

cv2.namedWindow('TrackBars')
cv2.resize("TrackBars", 640, 240)



img = cv2.imread(path)

imgHSV = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

cv2.imshow('Original', img)
cv2.imshow('HSV', imgHSV)
cv2.waitKey(0)
#will finish it later

In [ ]:
#FACE DETECTION


In [ ]:
import cv2 

faceCascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml') #this is a default file that we are using 
img = cv2.imread('Mouly.JPG')
imgGray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = faceCascade.detectMultiScale(imgGray, 1.1, 4) #we are going to find face using it

#going to create a bounding box around the faces that we detected and put a rectangle around them
for (x, y, w, h) in faces:
    cv2.rectangle(img,(x,y),(x+w, y+h), (225, 0, 0), 4)

cv2.imshow('Result', img)
cv2.waitKey(0)

In [ ]:
import cv2
 #this is a default file that we are using 
cap = cv2.VideoCapture('sampleTesting.mp4')
faceCascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

while True:
    success, img = cap.read()
    imgGray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = faceCascade.detectMultiScale(imgGray, 1.1, 4)
    
    
    
    for (x, y, w, h) in faces:
        p = x+(w//2)
        q = y+(h//2)
        var = f'{p} , {q}'
        cv2.rectangle(img,(x,y),(x+w, y+h), (0, 255, 0), 4)
        cv2.line(img, (1080//2,1920//2), (1080, 1920), (0,255,0), 3)
        cv2.putText(img, var, (x+200, y+200), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 150,0), 2)
        
        
        
    cv2.imshow('Video', img)
    if cv2.waitKey(1) & 0xFF == ord('m'):
        break

In [ ]:
# convert image to grayscale image
gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
 
# convert the grayscale image to binary image
ret,thresh = cv2.threshold(gray_image,127,255,0)
 
# calculate moments of binary image
M = cv2.moments(thresh)
 
# calculate x,y coordinate of center
cX = int(M["m10"] / M["m00"])
cY = int(M["m01"] / M["m00"])
 
# put text and highlight the center
cv2.circle(img, (cX, cY), 5, (255, 255, 255), -1)
cv2.putText(img, "centroid", (cX - 25, cY - 25),cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 2)
 
# display the image
cv2.imshow("Image", img)
cv2.waitKey(0)



In [ ]:
#face detection

In [ ]:
1. #Write a python program to detect your face and deviation of your face from the center of the frame using OpenCV.

In [ ]:
import cv2
import math
cap = cv2.VideoCapture(0) 
faceCascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml') #importing xml file

while True:
    success, img = cap.read()
    imgGray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = faceCascade.detectMultiScale(imgGray, 1.1, 4)
     
    for (x, y, width, height) in faces:
        pos1 = x+(width//2)
        pos2 = y+(height//2)
        w_shape = img.shape[1]//2
        h_shape = img.shape[0]//2
        eqn1 = pos1 - w_shape
        eqn2 = pos2 - h_shape
        #calculating the distance of the face
        distance = math.sqrt((eqn1)**2 + (eqn2)**2)
        #defining the rectangle
        cv2.rectangle(img,(x,y),(x+width, y+height), (0, 255, 0), 4)
        #line for indicating the center of the face
        cv2.line(img, (w_shape, h_shape), (pos1, pos2), (0,255,0), 3)
        #for face positions
        variable = 'Center'
        if eqn2 < 0:
            variable = 'Upward'
            if eqn1 > 0:
                variable += 'Right'
            else:
                variable += 'Left'
        elif eqn2 > 0:
            variable = 'Downward'
            if eqn1 > 0:
                variable += 'Right'
            else:
                variable += 'Left'
        #text for the distance
        cv2.putText(img, 'Distance :'+ str(int(distance)),(x+100,y+100), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 150,0), 2)
                
        #text for the position
        cv2.putText(img, 'Position: '+ variable, (x+100, y+150), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 150,0), 2)
        
        
        
    cv2.imshow('Output', img)
    if cv2.waitKey(1) & 0xFF == ord('m'):
        break