In [1]:
!pip install opencv-python

In [2]:
import cv2
print('Package imported')
img = cv2.imread('Mouly.JPG')
cv2.imshow('Output', img)
cv2.waitKey(1)


Package imported


-1

In [ ]:
import cv2
cap = cv2.VideoCapture('Cute Cat - 3092.mp4')
while True:
    success, img = cap.read()
    cv2.imshow('Video', img)
    if cv2.waitKey(1) & 0xFF == ord('m'):
        break

In [ ]:
import cv2
cap = cv2.VideoCapture(1)
cap.set(3, 640)
cap.set(4, 480)


while True:
    success, img = cap.read()
    cv2.imshow('Video', img)
    if cv2.waitKey(1) & 0xFF == ord('m'):
        break

In [ ]:
import cv2
import numpy as np
kernel = np.ones((5, 5), np.uint8)
img = cv2.imread('Mouly.JPG')
imgGray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
imgBlur = cv2.GaussianBlur(imgGray,(7,7), 0)
imgCanny = cv2.Canny(img, 150, 200)
imgDilation = cv2.dilate(imgCanny, kernel, iterations = 3)
imgerode = cv2.erode(imgDilation, kernel, iterations = 1)
cv2.imshow('GRAY Image', imgGray)
cv2.imshow('Blur Image', imgBlur)
cv2.imshow('Canny Image', imgCanny)
cv2.imshow('Dilate Image', imgDilation)
cv2.imshow('Eroder Image', imgerode)
cv2.waitKey(0)

In [ ]:
#openCV convention: x axis is same, y axis is towards.

In [ ]:
#resizing image:
import cv2
import numpy as np
img = cv2.imread('Mouly.JPG')
print(img.shape)                  #(6000---> weight, 4000 ---> height, 3---> BGR)
imgResize = cv2.resize(img, (200, 400))  #here, the weight comes first, then the height
print(imgResize.shape)            #(400, 200, 3)
imgCropped = img[0:2000, 200:900]            #here, the height comes first                
cv2.imshow('Image', img)
cv2.imshow('Resize Image', imgResize)
cv2.imshow('Cropped Image', imgCropped)
cv2.waitKey(0)


(6000, 4000, 3)
(400, 200, 3)


In [ ]:
#shapes and texts

In [ ]:
#we will use numpy library to create our img matrix
import cv2
import numpy as np

#img = np.zeros((512, 512))   #it will show a black img, which is gray scale image.
#print(img.shape)
img = np.zeros((512, 512, 3), np.uint8)
#print(img)       #it shows the matrix
#img[:] = 255, 0, 0     #it colors the whole image blue
img[200:600, 100: 500] = 255, 0, 0   #it shows only the portion as blue
print(img)


cv2.imshow('Image', img)
cv2.waitKey(0)


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [ ]:
#creating a line

import cv2
import numpy as np

img = np.zeros((512, 512, 3), np.uint8)
cv2.line(img, (0,0), (400, 400), (0,255,0), 3) #(0,0) starting point, (400, 400) end point, (0,255,0) color, 3--> thickness
#for creating the whole line in picture, we use 'img.shape()'
cv2.line(img,(0,0), (img.shape[1], img.shape[0],), (0, 255, 0), 3) #first width, then height
cv2.rectangle(img,(0,0), (250,350),(0,0,255), 2)
#cv2.rectangle(img,(0,0), (250,350),(0,0,255), cv2.FILLED) #for filling rectangle
cv2.circle(img,(400,50), 30, (255, 255, 0), 5) #(400, 50) center point, 30 --> radius, color, thickness
cv2.putText(img, 'Mouly', (200, 200), cv2.FONT_HERSHEY_COMPLEX, 1, (0, 150,0), 2) #1 --> scale(makes big-small), 2--> thickness
cv2.imshow('Image', img)
cv2.waitKey(0)

In [ ]:
#wrap prespective
import cv2
import numpy as np
img = cv2.imread('openCVking.jpg')

width, height = 250, 350
points = np.float32([[345,122],[580, 82],[409, 450],[636, 409]]) #we are taking four edges points from paints
points2 = np.float32([[0,0],[width, 0], [0,height], [width, height]])
matrix = cv2.getPerspectiveTransform(points, points2)
imgOutput = cv2.warpPerspective(img, matrix,(width, height))

cv2.imshow('Cards', img)
cv2.imshow('Output', imgOutput)
cv2.waitKey(0)

In [ ]:
#joining images(use stack)
import cv2
import numpy as np

img = cv2.imread('Mouly.JPG')
imgHor = np.hstack((img,img,img))
imgVer = np.vstack((img,img))

cv2.imshow('Horizontal',imgHor)
cv2.imshow('Vertical',imgVer)
cv2.waitKey(0)